version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pringales"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10gdb34700xi5"
s3_prefix = "pringales"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
